In [118]:
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
student_marks = [78, 47, 96, 55, 34]
print(student_marks)
print(item_list)

[78, 47, 96, 55, 34]
['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']


In [6]:
student_marks = [78, 47, 96, 55, 34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)


[83, 52, 101, 60, 39]


In [11]:
list1 = list(range(1,1000000))
list1


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [14]:
import numpy as np
a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b
print(c)

[      3       5       7 ... 1999995 1999997 1999999]


In [15]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr


array([78, 92, 36, 64, 89])

In [19]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
horsepower_arr


array([130, 165, 150, 150, 140])

In [20]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr


array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [21]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype

dtype('int32')

In [24]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [2]:
import numpy as np
car_attributes = [[[18, 15, 18, 16, 17],[130, 165, 150, 150, 140]],[[307, 350, 318, 304, 302],[7,9,6,29,90]]]
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[[ 18.  15.  18.  16.  17.]
  [130. 165. 150. 150. 140.]]

 [[307. 350. 318. 304. 302.]
  [  7.   9.   6.  29.  90.]]]
float64


In [3]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1:4]


array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U25')

In [33]:
list=[[1,2,3],[4,5,6],[7,8,9]]
print(list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [6]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
horsepower = [130,165,150,150,140]
acceleration= [18,15,18,16,17]
car_hp_acc_arr = np.array([cars,horsepower,acceleration])
car_hp_acc_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U25')

In [7]:
horsepower = [130,165,150,150,140]
horsepower_arr = np.array(horsepower)
print("Median horsepower =",np.median(horsepower_arr))

Median horsepower = 150.0


In [16]:
horsepower = [130,160,150,160,140]
horsepower_arr = np.array(horsepower)
print("Mean horsepower =",np.mean(horsepower_arr))

Mean horsepower = 148.0


In [15]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Minimum horsepower: ", np.min(horsepower_arr))
print("Maximum horsepower: ", np.max(horsepower_arr))



Minimum horsepower:  130
Maximum horsepower:  165


In [3]:
import numpy as np
horsepower = np.array([130,165,150,150,140])
x = np.where(horsepower>=150)
print (x)
print(horsepower[x])

(array([1, 2, 3], dtype=int64),)
[165 150 150]


In [19]:
import numpy as np 
student_marks =([67,45],[90,92],[66,72],[32,40])
student_array =np.array(student_marks)
print(student_arr)



[[67 45]
 [90 92]
 [66 72]
 [32 40]]


In [3]:
import numpy as np
array1=np.array([5, 10, 15])
array2=np.array([5])
array3= array1 * array2 
array3


array([25, 50, 75])

In [7]:
student_marks_arr = np.array([78, 92, 36, 64, 89])
print(np.sum(student_marks_arr))


359


In [9]:
additional_marks = [2, 2, 5, 10, 2]
student_marks_arr += additional_marks
student_marks_arr

array([82, 96, 46, 84, 92])

In [4]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
additional_marks = [2, 2, 5, 10, 2]
print(np.sum(student_marks_arr))
student_marks_arr += additional_marks
student_marks_arr



359


array([80, 94, 41, 74, 91])

In [13]:
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
students_marks += [5,10]
students_marks





array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

In [23]:
import numpy as np 
arr = np.linspace(0,10,50)
print(arr)
print('Length of arr: ',len(arr))



[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
Length of arr:  10


In [15]:
np.arange(0,100)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
np.arange(0,10,3)


array([0, 3, 6, 9])

In [28]:
print(np.linspace(0,10,3))


[ 0.  5. 10.]


In [5]:
import numpy as np
np.ones([1,2])

array([[1., 1.]])

In [2]:
import numpy as np
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
np.full(10,21)

array([21, 21, 21, 21, 21, 21, 21, 21, 21, 21])

In [5]:
np.full([3,10],'')


array([['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [12]:
np.full([9,3],"numpy")

array([['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy']], dtype='<U5')

In [6]:
np.add([1,2],[8,3])

array([9, 5])

In [7]:
import numpy as np
step_walk=([1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569])
array=np.array(step_walk)
array



array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [8]:
new_array=array[:,1]+2000
array[:,1]=new_array
array

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [12]:
sortedArr=arr[arr[:,1].argsort()]
print('sorted 2D Numpy Array')
print(sortedArr)

sorted 2D Numpy Array
[[1 2]
 [7 4]]


In [10]:
import numpy as np
arr=np.array([[1,2],[7,4],])
print(np.sum(arr))

14


In [13]:
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[8 6]
[ 3 11]


In [14]:
arr=np.array([[1,2],[3,4]])
print(np.mean(arr))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [15]:
arr=np.array([[1,2],[9,0]])
print(np.median(arr))


1.5


In [16]:
arr=np.array([[1,2],[9,7]])
print(np.min(arr))

1


In [17]:
arr=np.array([[1,2],[8,0]])
print(np.max(arr))

8


In [18]:
import numpy as np
arr = np.array([[1, 2], [3, 9]])
print(np.max(arr)) 
print(np.max(arr, axis=0)) 
print(np.max(arr, axis=1)) 

9
[3 9]
[2 9]


In [19]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.median(arr))
print(np.median(arr, axis=0)) 
print(np.median(arr, axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [20]:
import numpy as np
arr = np.array([[1, 7], [3, 4]])
print(np.prod(arr)) 

84


In [21]:
print(np.prod(arr, axis=0))
print(np.prod(arr, axis=1))

[ 3 28]
[ 7 12]


In [22]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.std(arr))
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))

1.118033988749895
[1. 1.]
[0.5 0.5]


In [120]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.var(arr))
print(np.var(arr, axis=0))
print(np.var(arr, axis=1)) 

1.25
[1. 1.]
[0.25 0.25]


In [121]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result) 

[5 7 9]


In [122]:
import numpy as np
arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print(result) 

[3 3 3]


In [123]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result) 

[ 4 10 18]


In [124]:
import numpy as np
arr1 = np.array([4, 6, 8])
arr2 = np.array([2, 3, 4])
result = arr1 / arr2
print(result)

[2. 2. 2.]


In [125]:
import numpy as np
arr = np.array([2, 3, 4])
result = arr ** 2
print(result) 

[ 4  9 16]


In [126]:
import numpy as np
arr = np.array([4, 9, 16])
result = np.sqrt(arr)
print(result)

[2. 3. 4.]


In [127]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 3])
result = arr1 == arr2
print(result) 

[False  True  True]


In [130]:
#statistical function
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_mean = np.mean(arr)

In [133]:
#statistical function
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_mean = np.mean(arr)
result_std = np.std(arr, axis=1)
result_sum = np.sum(arr, axis=0)
print(result_std) 
print(result_mean) 
print(result_sum) 

[0.81649658 0.81649658]
3.5
[5 7 9]


In [135]:
#Element-wise rounding
import numpy as np
arr = np.array([2.3, 4.4, 6.1])
result = np.round(arr)
print(result) 

[2. 4. 6.]


In [136]:
#Element-wise exponentiation with a scalar
import numpy as np
arr = np.array([2, 3, 4])
result = np.power(arr, 2)
print(result) 

[ 4  9 16]


In [137]:
#Element-wise comparison and conditional assignment
import numpy as np
arr = np.array([1, 5, 10])
result = np.where(arr > 5, arr, 0)
print(result)

[ 0  0 10]


In [138]:
#Element-wise cumulative sum
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = np.cumsum(arr)
print(result) 

[ 1  3  6 10 15]


In [139]:
#Element-wise sorting
import numpy as np
arr = np.array([3, 1, 4, 2, 5])
result = np.sort(arr)
print(result)

[1 2 3 4 5]


In [143]:
#Vectorized operations Exercise
S_X = np.array([[1, 5, 6, 5],[4, 8, 6, 5]])
S_Y = np.array([[6, 7, 5, 9],[7, 5, 6, 4]])
quarterly_difference = S_Y - S_X
print(quarterly_difference)


[[ 5  2 -1  4]
 [ 3 -3  0 -1]]


In [144]:
#Quarters having a literacy rate less than 2
less_than_2 = S_X < 2
print(less_than_2)

[[ True False False False]
 [False False False False]]


In [149]:
#squaring each number using map()
numbers = [1, 2, 3, 4, 5]
squared_numbers = map(lambda x: x ** 2, numbers)
print(list(squared_numbers)) 

[1, 4, 9, 16, 25]


In [150]:
#filtering even numbers using filter()
numbers = [1, 2, 3, 4, 5]
even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers))

[2, 4]


In [151]:
from functools import reduce
numbers = [1, 2, 3, 4, 5]
# Summing all the numbers using reduce()
sum_of_numbers = reduce(lambda x, y: x + y, numbers)
print(sum_of_numbers)


15


In [2]:
square = lambda x: x ** 2
print(square(6)) 

36


In [1]:
import numpy as np
step_walk=([1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569])
array=np.array(step_walk)
array


array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])